import { Comic } from "@/features/characters/models";
import {
  DateType,
  Extension,
  Format,
  ItemType,
  PriceType,
  Result,
  Role,
  URLType,
} from "../interfaces/comics.interface";

export const mockApiResultsComic: Result[] = [
  {
    id: 1,
    digitalId: 123456,
    title: "Test Comic 1",
    issueNumber: 1,
    variantDescription: "Variant Description",
    description: "Test description",
    modified: "2022-01-01T00:00:00Z",
    isbn: "1234567890",
    upc: "123456789012",
    diamondCode: "ABCD1234",
    ean: "9876543210987",
    issn: "1234-5678",
    format: Format.Comic,
    pageCount: 10,
    textObjects: [],
    resourceURI: "http://example.com/comic/1",
    urls: [{ type: URLType.Detail, url: "http://example.com/detail" }],
    series: { resourceURI: "http://example.com/series/1", name: "Series 1" },
    variants: [],
    collections: [],
    collectedIssues: [],
    dates: [{ type: DateType.OnsaleDate, date: "2022-01-01T00:00:00Z" }],
    prices: [{ type: PriceType.PrintPrice, price: 3.99 }],
    thumbnail: { path: "http://example.com/image", extension: Extension.Jpg },
    images: [{ path: "http://example.com/image", extension: Extension.Jpg }],
    creators: {
      available: 1,
      collectionURI: "http://example.com/creators",
      items: [
        {
          resourceURI: "http://example.com/creator/1",
          name: "Creator 1",
          role: Role.Writer,
        },
      ],
      returned: 1,
    },
    characters: {
      available: 0,
      collectionURI: "http://example.com/characters",
      items: [],
      returned: 0,
    },
    stories: {
      available: 1,
      collectionURI: "http://example.com/stories",
      items: [
        {
          resourceURI: "http://example.com/story/1",
          name: "Story 1",
          type: ItemType.Cover,
        },
      ],
      returned: 1,
    },
    events: {
      available: 0,
      collectionURI: "http://example.com/events",
      items: [],
      returned: 0,
    },
  },
  {
    id: 2,
    digitalId: 123456,
    title: "Test Comic 2",
    issueNumber: 1,
    variantDescription: "Variant Description",
    description: "Test description",
    modified: "2023-01-01T00:00:00Z",
    isbn: "1234567890",
    upc: "123456789012",
    diamondCode: "ABCD1234",
    ean: "9876543210987",
    issn: "1234-5678",
    format: Format.Comic,
    pageCount: 10,
    textObjects: [],
    resourceURI: "http://example.com/comic/1",
    urls: [{ type: URLType.Detail, url: "http://example.com/detail" }],
    series: { resourceURI: "http://example.com/series/1", name: "Series 1" },
    variants: [],
    collections: [],
    collectedIssues: [],
    dates: [{ type: DateType.OnsaleDate, date: "2022-01-01T00:00:00Z" }],
    prices: [{ type: PriceType.PrintPrice, price: 3.99 }],
    thumbnail: { path: "http://example.com/image", extension: Extension.Jpg },
    images: [{ path: "http://example.com/image", extension: Extension.Jpg }],
    creators: {
      available: 1,
      collectionURI: "http://example.com/creators",
      items: [
        {
          resourceURI: "http://example.com/creator/1",
          name: "Creator 1",
          role: Role.Writer,
        },
      ],
      returned: 1,
    },
    characters: {
      available: 0,
      collectionURI: "http://example.com/characters",
      items: [],
      returned: 0,
    },
    stories: {
      available: 1,
      collectionURI: "http://example.com/stories",
      items: [
        {
          resourceURI: "http://example.com/story/1",
          name: "Story 1",
          type: ItemType.Cover,
        },
      ],
      returned: 1,
    },
    events: {
      available: 0,
      collectionURI: "http://example.com/events",
      items: [],
      returned: 0,
    },
  },
];

export const mockAdaptedComics: Comic[] = [
  {
    id: 1,
    image: "http://example.com/image/portrait_fantastic.jpg",
    onSaleDate: new Date("2022-01-01T00:00:00Z"),
    title: "Test Comic 1",
  },
  {
    id: 2,
    image: "http://example.com/image/portrait_fantastic.jpg",
    onSaleDate: new Date("2023-01-01T00:00:00Z"),
    title: "Test Comic 2",
  },
];
